### ISSUE TITLE
Error when activating workflow: "Could not get parameter "pollTimes"!"

### ISSUE THREAD

**Issue by joeldeteves** [Joffcom/n8n-nodes-rss-feed-trigger#6] opened 2022-10-12 03:59 UTC
I'm testing this now using n8n 0.196.0 and when I try to activate the workflow, I get the following error:

_There was a problem activating the workflow: "Could not get parameter "pollTimes"!"_

It works fine if I run it manually.

**Comment by joeldeteves** [comment] 2022-10-12 04:11
Adding to this: It seems the Poll Times field is missing from the latest version of the node.

![image](https://user-images.githubusercontent.com/33190570/195248115-40d5e2ab-2faf-4199-8cb7-ee9affa7d075.png)

**Comment by Joffcom** [comment] 2022-10-12 10:19
Hey @joeldeteves,

Oddly enough I had that issue with an older version of the node, Which version do you currently have installed?

**Comment by joeldeteves** [comment] 2022-10-12 14:27
> Hey @joeldeteves,
> 
> 
> 
> Oddly enough I had that issue with an older version of the node, Which version do you currently have installed?

I've tried all three currently available versions of the node. I've also tried updating n8n -> 0.197.1. Same issue

**Comment by Joffcom** [comment] 2022-10-12 14:59
Hey @joeldeteves,

There was a report earlier where someone has made a Google Sheets Trigger node using the same method and for them refreshing the container did the job. Out of interest does that work for you as well?

Assuming you are using a container...

**Comment by joeldeteves** [comment] 2022-10-12 15:13
Yes we run in k8s so it's a container environment (using the official n8n image). However it's been redeployed multiple times (most recently to upgrade to version 0.197.1) - same issue unfortunately

**Comment by Joffcom** [comment] 2022-10-12 15:35
Sadly I am out of ideas at the moment, The poll times come from the internal `IPollFunctions` so it isn't really something that is controlled by the node.

I do need to make a tweak to this node though so I will try a couple of things and see if it makes any difference, I do think there might be a bit of an internal n8n bug when using polling triggers as community nodes that I need to look into at some point.

**Comment by joeldeteves** [comment] 2022-10-12 15:58
Is there anything I can provide from my end to assist you? Logs / console output from the browser / etc?

**Comment by Joffcom** [comment] 2022-10-12 16:32
Hey @joeldeteves,

I would love to say yes, But at the moment nothing. I would be interested to know if it shows in a new workflow when using private browsing mode though.

**Comment by joeldeteves** [comment] 2022-10-12 16:50
Hi @Joffcom I did try a private browser window and a new workflow and I have the same problem.

I also tried Firefox and got the same result, so it's not specific to Chrome / Firefox or any extensions that I'm running.

**Comment by Joffcom** [comment] 2022-10-12 19:58
Hey @joeldeteves,

That is annoying, I ended up working on another node tonight so this one will have to wait until tomorrow evening for a update.

**Comment by joeldeteves** [comment] 2022-10-12 20:14
Happy to help however I can. Thanks Jon,

**Comment by xlucasfelix** [comment] 2022-10-26 16:55
Any update on this? I have the same problem here (Feed to Discord)

**Comment by Joffcom** [comment] 2022-10-26 19:14
Hey @xlucasfelix,

Not yet, it is a bit of an odd one. It is working ok on a couple of the installs I am running but sometimes I see it happen.

Still need to properly dig into it.

**Comment by mightworks** [comment] 2022-10-28 17:17
Same issue here!

**Comment by Joffcom** [comment] 2022-10-28 18:42
Hey @mightworks,

What version of n8n are you running?

**Comment by joeldeteves** [comment] 2022-10-28 18:47
I've switched to Queue Mode @Joffcom - if you can tell me how to install community nodes manually I'll give this another go (running 0.200.0)

**Comment by mrhappyma** [comment] 2022-11-01 01:58
I am also having the same issue with a feed to Discord

**Comment by Joffcom** [comment] 2022-11-01 05:11
Hey @mrhappyma,

What version of n8n are you running?

**Comment by mrhappyma** [comment] 2022-11-01 18:35
> Hey @mrhappyma,
> 
> What version of n8n are you running?

0.199.0

**Comment by Joffcom** [comment] 2022-11-15 18:05
Would you be able to try updating to see if it works now?

**Comment by mrhappyma** [comment] 2022-11-16 13:11
I updated and lost all my data 😭 
I had workflow backups, I'll try this out once I have everything set up again.

**Comment by Joffcom** [comment] 2022-11-16 13:18
Hey @mrhappyma,

Was that from updating the node or n8n? Normally dataloss would happen when updating n8n if Docker is being used and the volume has not been configured correctly to persist the data.

**Comment by mrhappyma** [comment] 2022-11-16 15:14
Yeah, I was having other issues with my Docker setup too. Getting those sorted out.

**Comment by kpatdev** [comment] 2022-11-20 02:21
Hey just wanted to chime in and say that I am having the same issue. Updated everything and still same issue. Sending output from RSS update to Discord.

n8n `v0.203.1`
n8n-nodes-rss-feed-trigger `v0.1.3`

**Comment by Joffcom** [comment] 2022-11-20 05:47
Hey @dezerving,

Are you running in Docker? At this point I think it is worth trying to find out about the different setups as this appears to be working for a few installs but failing for others which makes no sense.

Would you be able to restart n8n again and open the browser dev console and add the node to a new workflow and share the output of there are any errors?

**Comment by kpatdev** [comment] 2022-11-20 07:15
> Hey @dezerving,
> 
> Are you running in Docker? At this point I think it is worth trying to find out about the different setups as this appears to be working for a few installs but failing for others which makes no sense.
> 
> Would you be able to restart n8n again and open the browser dev console and add the node to a new workflow and share the output of there are any errors?

Yes I am running in Docker (on Unraid). Sure I will give that a go and update here tomorrow morning.

**Comment by mrhappyma** [comment] 2022-11-20 20:18
Mine was in Docker, [Coolify](https://coolify.io) on Ubuntu

**Comment by benborges** [comment] 2022-11-28 17:32
Same here, I'm using cloudron.io stack (docker) have the exact same issue when adding this node to my N8N instance
- already rebooted container

**Comment by n0k0m3** [comment] 2022-12-14 04:18
I think the problem is due to old n8n-core and n8n-workflow. Can you update them to latest version?

**Comment by Joffcom** [comment] 2022-12-14 07:02
@n0k0m3 the last release was mostly a version bump and for my installs and a few others I have seen all is working fine.

The timings are automatically added and have been there to use for over a year. I am starting to think there might be some conflict somewhere else.

Are you having the same issue and what version of n8n are you running and how is it running?

**Comment by n0k0m3** [comment] 2022-12-14 15:23
n8n: 0.207.1, docker

So... ye I think it's the problem of the docker deployment

Update: changed image to `latest-debian` tag and it worked, so definitely it's alpine docker image problem

**Comment by Joffcom** [comment] 2022-12-14 19:50
@n0k0m3 that is interesting, to make things more confusing all docker installs I have tested with have been using the alpine based image.

I think we might have an issue in our core somewhere but I have not found it yet and other nodes we have that use the same method are all good as well.

Knowing the deb image works though is handy and maybe a temporary solution for anyone wanting to use it.

**Comment by n0k0m3** [comment] 2022-12-14 21:15
So if you already have workflow node with polltime setup properly, then changing to alpine docker it'll still work and have polltime. But if you create a new node in a new workflow (in alpine deployment) it'll not have polltime field

**Comment by Joffcom** [comment] 2022-12-14 21:19
I wish it was that simple, I had it working with a fresh docker image but I had to do a restart after saving the workflow.

It is very odd.

**Comment by isudoi** [comment] 2022-12-28 19:59
btw, I had the same issue here, but after upgrading my docker compose stack for n8n to the latest # `Version: 0.209.3`

It's activated successfully now.


![Screenshot 2022-12-28 at 2 58 28 PM](https://user-images.githubusercontent.com/5244872/209865813-9e8d5b10-c085-4595-a2ef-36d10492660b.png)

**Comment by Joffcom** [comment] 2022-12-30 11:16
That is good news, I had a chat with a community member on Discord and they have it working without having to mess around as well so it looks like everything should be all good.

**Comment by deya-0x** [comment] 2022-12-31 19:25
I had this issue, but once I restarted n8n after installing this package, it started working.

**Comment by Juijote** [comment] 2023-02-01 04:03
> I had this issue, but once I restarted n8n after installing this package, it started working.

I'm in the same boat, and suggest that the developers add a prompt in the user guide that you need to restart after installing the node.

**Comment by Joffcom** [comment] 2023-02-03 08:38
@Juijote oddly enough it shouldn't need a restart but I will pop a note in the node itself.

**Comment by isudoi** [comment] 2023-03-25 04:48
@Joffcom issue is back after updating docker n8n to 0.221.2

Any idea if someone else reporting the issue.

Already tried to restart twice the container with no luck

**Comment by Joffcom** [comment] 2023-03-25 05:04
Hey there,

The issue is not with the node itself and was down to a change internally in n8n, this has been fixed we just need to wait for the next release of n8n.

**Comment by mrhappyma** [comment] 2023-03-31 01:54
Looks like this is fixed with [0.222.0](https://github.com/n8n-io/n8n/releases/tag/n8n%400.222.0)

**Comment by Joffcom** [comment] 2023-03-31 04:03
Yeah, hopefully this will be the last time we see this one 🙂

I think it is time to finally close this one.

**Closed as completed** 2023-03-31 04:03 UTC

**Comment by pablorq** [comment] 2023-10-03 09:08
Same issue with n8n v1.8.2.

Any idea how to fix it?

**Comment by Joffcom** [comment] 2023-10-03 11:54
Hey @pablorq,

Can you restart n8n after installing the node that should get the poll times displaying.

**Comment by pablorq** [comment] 2023-10-03 12:41
> Hey @pablorq,
> 
> Can you restart n8n after installing the node that should get the poll times displaying.

It seems to work, restarting the docker container.

Thank you!
